controller:
    deployment:
        image:
            repository: quay.io/pipelines-feedback/tekton
            pullPolicy: Always

rbac:
    jobRules: 
        - apiGroups: ["tekton.dev"]
          resources: ["pipelineruns", "taskruns", "pipelines"]
          verbs: ["list", "get", "watch"]
