---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
    name: test-run
    annotations:
        pipelinesfeedback.keskad.pl/https-repo-url: "https://github.com/keskad/jx-gitops"
        pipelinesfeedback.keskad.pl/commit: "76ea7c746d4e4ac42c44bf72946d3b0d399553dd"
        pipelinesfeedback.keskad.pl/ref: "refs/heads/test-pr"
        pipelinesfeedback.keskad.pl/pr-id: "2"
spec:
    pipelineSpec:
        tasks:
            - name: clone
              taskSpec:
                  params:
                      - name: username
                        default: $(params.username)
                  steps:
                      - image: ghcr.io/containerd/busybox:1.36
                        name: print
                        script: |
                            sleep 3
                            echo "Bread for you, $(params.username)"
                            sleep 5

            - name: test
              taskSpec:
                  steps:
                      - image: busybox
                        name: print
                        script: |
                            sleep 10
                            echo "Waited 10 seconds"
                            /bin/true
    params:
        - name: username
          value: "Kropotkin"
