name: Test and release
on:
    push:
        tags:
            - "*"
        branches:
            - main
    pull_request:

jobs:
    build:
        uses: kube-cicd/.github/.github/workflows/app.common.yaml@main
        secrets:
            containerRegistryUsername: "${{ secrets.QUAY_USERNAME }}"
            containerRegistryPassword: "${{ secrets.QUAY_PASSWORD }}"
        with:
            containerImage: "quay.io/pipelines-feedback/tekton"
            containerRegistryHost: "quay.io"
            testCommand: "make k3d k3d-install-tekton test"
            goVersion: "1.22"

    release-helm:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: kube-cicd/.github/.github/workflows/helm.common.yaml@main
        needs: ["build"]
        secrets:
            registryUsername: "${{ secrets.QUAY_USERNAME }}"
            registryPassword: "${{ secrets.QUAY_PASSWORD }}"
        with:
            chartRepoName: "pipelines-feedback"
            chartName: "tekton-chart"
            chartPath: "charts/tekton-chart"
            enableHelmDocs: false
            registryHost: "quay.io"
